title: BdTechBlog
author: Dr. Nobel Khandaker
email: your-email@domain.com
description: > # this means to ignore newlines until "show_exerpts:"
  Blog about scalable software engineering.  Contains solutions to real-world software development, QA, deployment, service maintenance problems.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "" #/nobelk.github.io

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Dr. Nobel Khandaker
  tagline: VP Technology (Ex. Microsoft Lead Senior Software Engineer)
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false
  navigation:
    - title: My Work
      url: "/my-work"
    - title: Resume
      url: "/resume"

  # generate social links in footer
  social_links:
    github:  nobelk
    linkedIn: in/nobelkhandaker
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed